# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.9.6"
      node_js: 14
      addons:
        sonarcloud:
          organization: swsnu

      install:
        - cd Backend
        - cd team18
        - pip install -r requirements.txt
        - cd ..
        - pip install coveralls
        - gem install coveralls-lcov
        - pip install Pillow==8.4
        - cd ..
        - cd Frontend/ooo
        - yarn install
        - yarn global add coveralls
        - cd ../..
      script:
        - cd Frontend/ooo
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - coveralls-lcov -v -n coverage/lcov.info > ../coverage.json
        - cd ../..
        - cd Backend/team18
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test --keepdb
        - coverage xml
        - coveralls --merge=../../Frontend/coverage.json
        - cd ../..
        - sonar-scanner
