# CI Environment
dist: bionic

# Job Configurations
jobs:
  include:
    - language: python
      python: "3.9.6"
      install:
        - cd Backend
        - pip install -r requirements.txt
        - cd ooo
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd .. && sonar-scanner

    - language: node_js
      node_js: 14
        addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "yqeI7PKVh1pw90BcuIPJj1xLZ7NHtonx/s2bYJDpE5uEK1Wt+gX9tXIl12V2db+XDQymc+t65XQ6gD8vgAveSibRUO2cNLBckLMnZZy5dvKs5h+S22s/ETXE4DRHm2kiw57opFVx+EPcrQVvSQ75wk0OEFALI3RhCLeNbe1HS2np6JE+EV9cwj0pt579YRz3/Vqap3847wfjpuOZEjCNVmI/pA6QEY0TdQ4qu5HBE2qyB8SMw8Htjv/DnW4pnvLWIlh6n5IZVt9r6tA7Q+aocvo4YhnRCIEh3Ln7EhZF/QvYn0tBxJjqA01VSp15RwUUfaQ+1jilxvrWIn6hd5fdSaRAZdLXJ9Pb6chrm1+D7K+XZnmbFRf3GGBrai5NbrfL9bgkDpPUCo0RpkJFRp7NJwrt61DUQc2/6vEnXLtiB6knDsKvG5XOPwKMtI+oghq4A4rfpnZH0ixnKRoyRCCxV3G038kmKwltcOWi7DVJ7EaYJF7/3gZ+rdlouKtTeH8j28lhECT1kNw6e4LcbF+mtOk3ns760RRRQVBYdWdppk/+CFCWNJb4rJ4GmT5vdEIYVyHctn7QL8gwkA7+Zi4sGJ/yytsdzXthHWi++DVFcMQCc0Qh7ioNj6mqXsInLR9bJCLOvSiK8DIrZjx1l/LI4dUNz9ez2JDn/ciJu7Gj8BY=" # encrypted value of your token
      install:
        - cd Frontend/ooo
        - yarn install
      script:
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner
